# 03-mongodb-pvc.yaml
# Binds MongoDB storage in the easyshop namespace to the PV (mongodb-pv).

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: easyshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
