# 11-migration-job.yaml
# One-off Job to run DB migrations against mongodb-service before or after app deploy.
# restartPolicy OnFailure retries the pod if migration exits with an error.

apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
      - name: migration
        image: simsoliver/easyshop-migration:6
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
